# Generated by Django 3.1.6 on 2021-02-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
